baseURL: https://murphywzhu.github.io/blog/
languageCode: zh-cn
defaultContentLanguage: zh-cn
title: 锦酱的博客
theme: "PaperMod"
languages:
    zh-cn:
        languageName: "简体中文"
        weight: 1
        menu:
            main:
                - name: 搜索
                  url: search/
                  weight: 10
                - name: 标签
                  url: tags/
                  weight: 10

params:
    profileMode:
        enabled: true
        title: "锦酱" # optional default will be site title
        subtitle: "锦酱!别哭啦，眼睛都肿啦!"
        imageUrl: "https://mublog.oss-cn-beijing.aliyuncs.com/mutx.jpeg" # optional
        imageTitle: "图片被吃掉了哎!" # optional
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size
        buttons:
            - name: 文章
              url: "posts/"
            - name: Github
              url: "https://github.com/murphywzhu"
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary



